### ISSUE TITLE
Segmentation fault (core dumped) when running any move2kube command

### ISSUE THREAD

**Issue by PatrickGeyer** [konveyor/move2kube#816] opened 2022-06-19 23:16 UTC
**Describe the bug**
Segmentation fault (core dumped) when running move2kube
**To Reproduce**
CentOs, newest version of move2kube

**Expected behavior**
converts kubernetes files in folder to docker-compose file.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Centos
 - Cant get version number due to same error

**Comment by ashokponkumar** [comment] 2022-06-20 03:41
@HarikrishnanBalagopal Can you please check this out?

**Comment by HarikrishnanBalagopal** [comment] 2022-06-20 07:48
@PatrickGeyer Hi, Thanks for making a bug report.
```
Cant get version number due to same error
```
Can you tell us how you installed `move2kube` please?

**Comment by HarikrishnanBalagopal** [comment] 2022-06-20 17:48
Ok so I recompiled `move2kube` on CentOS and ran it
```
# move2kube version -l
version: v0.3.2
gitCommit: ef9f59dcf5c90aab70450b3a092dd5cad2832018
gitTreeState: clean
goVersion: go1.17.5
```
So since it's not seg faulting it might be some issue of cross compiling in our release pipeline.

**Comment by ashokponkumar** [comment] 2022-06-20 18:05
> @PatrickGeyer Hi, Thanks for making a bug report.
> ```
> Cant get version number due to same error
> ```
> Can you tell us how you installed `move2kube` please?
> ```
> CentOs, newest version of move2kube
> ```
> Do you mean `v0.3.2` ? https://github.com/konveyor/move2kube/releases/tag/v0.3.2
> ```
> Segmentation fault (core dumped) when running move2kube
> ```
> Usually there's some panic error message when this happens in Golang. Can you post any/all of the terminal output please?
> ```
> converts kubernetes files in folder to docker-compose file.
> ```
> Also if you can provide a small sample input to reproduce the bug, that would be great!
> 
> Update:
> ```
> # ./move2kube version -l
> Segmentation fault (core dumped)
> ```
> I was able to reproduce the bug with v0.3.2 linux amd64 executable https://github.com/konveyor/move2kube/releases/download/v0.3.2/move2kube-v0.3.2-linux-amd64.tar.gz
> on CentOS
> ```
> # cat /etc/os-release
> NAME="CentOS Stream"
> VERSION="9"
> ID="centos"
> ID_LIKE="rhel fedora"
> VERSION_ID="9"
> PLATFORM_ID="platform:el9"
> PRETTY_NAME="CentOS Stream 9"
> ANSI_COLOR="0;31"
> LOGO="fedora-logo-icon"
> CPE_NAME="cpe:/o:centos:centos:9"
> HOME_URL="https://centos.org/"
> BUG_REPORT_URL="https://bugzilla.redhat.com/"
> REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
> REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
> ```
> However this bug doesn't occur on Ubuntu 20.04 with the same executable file.

Is it reproductive with the latest rc build? If it is an issue with golang, it might have been fixed in the latest builds.

**Comment by HarikrishnanBalagopal** [comment] 2022-06-21 05:32
@PatrickGeyer Hi, I have recompiled for Linux and attached the new binary to the `v0.3.2` release
https://github.com/konveyor/move2kube/releases/download/v0.3.2/move2kube-v0.3.2-recompiled-for-linux-amd64.tar.gz

Please download that and use it for now while we fix this bug. It is tested and working for me on:
```
# cat /etc/os-release
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

# ./move2kube version -l
version: v0.3.2
gitCommit: ef9f59dcf5c90aab70450b3a092dd5cad2832018
gitTreeState: clean
goVersion: go1.18.3
```

**Comment by HarikrishnanBalagopal** [comment] 2022-06-21 06:02
@PatrickGeyer Hi, looking at the StackOverflow thread that you were on https://stackoverflow.com/questions/58939778/convert-kubernetes-config-to-docker-compose-file-reverse-kompose/64143453
the feature that you need is only in v2 for now. It will be added to v3 later.

So I have recompiled `v0.2.0` and uploaded it to the release https://github.com/konveyor/move2kube/releases/download/v0.2.0/move2kube-v0.2.0-recompiled-for-linux-amd64.tar.gz
I have tested it and it works on CentOS:
```
# cat /etc/os-release
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

# ./move2kube version -l
version: v0.2.0
gitCommit: 8a4e2b89f0908e08fa817467bf4cecfcb9649cc9
gitTreeState: clean
goVersion: go1.18.3
```

**Comment by HarikrishnanBalagopal** [comment] 2022-08-11 08:52
Closing since this was fixed

**Closed by HarikrishnanBalagopal** 2022-08-11 08:52 UTC

**Comment by HarikrishnanBalagopal** [comment] 2023-06-09 12:01
Fixed by https://github.com/konveyor/move2kube/pull/817
