### ISSUE TITLE
Docker images have to be small case. docker-image-build script does not ensure this.

### ISSUE THREAD

**Issue by seshapad** [konveyor/move2kube#469] opened 2021-04-06 06:32 UTC
**Describe the bug**
The shell script for docker image build does not make sure that the image name has to be small-case. If the source folder name is camel-case or capitalized, it gets dumped as is into the shell script.

**Comment by ashokponkumar** [comment] 2021-06-21 13:29
Duplicate of #507

**Closed** 2021-07-06 15:39 UTC
Labels: bug
